scan-type: source
disabled: false
ignore:
  - vulnerability: GHSA-52f5-9888-hmc6
    package:
      name: tmp
      version: 0.0.33
    reason: >-
      Low vulnerability only used in tests. ioredis-mock@8.12.0 requires tmp@^0.0.33 via fengari@0.1.4. No patched
      version available for tmp.
  - vulnerability: GHSA-mh99-v99m-4gvg
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: brace-expansion (high severity) as of 2026-09-17'
  - vulnerability: GHSA-rgw5-rvv9-x895
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: brace-expansion (high severity) as of 2026-09-17'
output:
  - table
  - json
quiet: false
check-for-app-update: false
only-fixed: false
add-cpes-if-none: false
by-cve: false
db:
  auto-update: true
  validate-age: true
  max-allowed-built-age: 120h
