version: "3.9"

# @see https://uninterrupted.tech/blog/hassle-free-redis-cluster-deployment-using-docker/
x-redis-node: &REDIS_NODE
  image: docker.io/bitnami/redis-cluster:6.2.14
  environment: &REDIS_ENVS
    ALLOW_EMPTY_PASSWORD: yes
    REDIS_CLUSTER_DYNAMIC_IPS: no
    REDIS_CLUSTER_ANNOUNCE_IP: ${REDIS_CLUSTER_ANNOUNCE_IP}
    REDIS_NODES: localhost:${REDIS_CLUSTER_PORT} localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
  healthcheck:
    test: [ "CMD", "redis-cli", "ping" ]
    timeout: 2s
  network_mode: host

services:
  redis-node-0:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_CLUSTER_CREATOR: yes
      REDIS_PORT_NUMBER: ${REDIS_CLUSTER_PORT}
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5

  redis-node-1:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_PORT_NUMBER: 6380
    ports:
      - "16380:16380"
  redis-node-2:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_PORT_NUMBER: 6381
    ports:
      - "16381:16381"
  redis-node-3:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_PORT_NUMBER: 6382
    ports:
      - "16382:16382"
  redis-node-4:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_PORT_NUMBER: 6383
    ports:
      - "16383:16383"
  redis-node-5:
    <<: *REDIS_NODE
    environment:
      <<: *REDIS_ENVS
      REDIS_PORT_NUMBER: 6384
    ports:
      - "16384:16384"

  redis:
    image: redis:6.2.4-alpine
    restart: "unless-stopped"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    ports:
      - "${REDIS_STANDALONE_PORT}:6379"
