version: "3.9"

services:
  redis:
    image: redis:6.2.4-alpine
    #    image: redis/redis-stack:latest
    restart: "unless-stopped"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_TLS_ENABLED=no
    ports:
      - "${REDIS_PORT}:6379"
